### ISSUE TITLE
Interface/Documentation for fetching swap Txns?

### ISSUE THREAD

**Issue by PhilGabardo** [reach-sh/humble-sdk#36]
My use case requires an interface for fetching the transactions required for performing a given swap, but the SDK does not support this as far as I can tell. Documentation for the transactions (eg. what application args should be supplied to the second transaction) would also suffice.

**Comment by cbaunach** [comment]
It sounds like this is the part of the documentation that you are looking for (it deals with swapping tokens):
https://reach-sh.github.io/humble-sdk/SWAPPING.html#swaptokens

This portion deals with the SwapTxnOpts that specify the application args needed to trigger the swapTokens function:
https://reach-sh.github.io/humble-sdk/TYPES.html#swaptxnopts

And here is a link to the swapTokens function in the code for further context:
https://github.com/reach-sh/humble-sdk/blob/7368e1ebd0223b7c2511260f9169b8fd0b8e45f1/src/api/Trader.Swap.ts#L17

Also, if you want to see the function in action you can clone the repository, cd into the cli directory, and run `npm run test` to try out various functionalities like swaping, listing pools, etc

Do those answer your question or were you looking for a different kind of interface for swapping tokens?

Your question also just uncovered a gap in the docs; we need to update the initHumbleSDK params with the ReachEnvOpts. Those ReachEnvOpts specify the wallet (myAlgo or Pera wallet) the user will use to sign the transactions triggered by calling the swapTokens function. Thank you for bringing this to our attention!

**Comment by MrJackdaw** [comment]
Hey @PhilGabardo; I just gave a more-involved explanation of swapping [**here**](https://github.com/reach-sh/humble-sdk/issues/43#issuecomment-1169386799). If your issue has not yet been resolved, can you take a look and let me know if it helps?

**Comment by PhilGabardo** [comment]
Hey @MrJackdaw I was able to resolve it, thanks

**Comment by MrJackdaw** [comment]
Thanks for the update! Let us know if you need any more help; I'll mark this resolved in the meantime.
