### ISSUE TITLE
"Error: An unknown git error occurred" when installing via npm from Windows environment [SOLVED]

### ISSUE THREAD

**Issue by LogioTek** [reach-sh/humble-sdk#37]
npm install @reach-sh/humble-sdk
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

...
639 verbose stack Error: An unknown git error occurred
639 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
639 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
639 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
...

Tried it on 2 separate x86-64 machines up to date with Windows 10 and 11 with the same outcome.

npm -v
8.8.0

node -v
v18.1.0

**Comment by LogioTek** [comment]
Solved the issue by installing Git for Windows and rebooting.

**Comment by MrJackdaw** [comment]
Hey thanks for updating this; I'm closing since you marked it as "solved".
