### ISSUE TITLE
package.json "build" script references "rm -rf" which fails on Windows environment [SOLVED]

### ISSUE THREAD

**Issue by LogioTek** [reach-sh/humble-sdk#38]
npm run build

@reach-sh/humble-sdk@2.0.0 build
rm -rf lib/ && tsc

'rm' is not recognized as an internal or external command,
operable program or batch file.

I manage to get it to build by omitting the removal of lib directory and just executing only "tsc"

**Comment by LogioTek** [comment]
Does not seem to be an issue with #37 resolved.

**Comment by MrJackdaw** [comment]
Hey thanks for updating this; I'm closing as well since you marked it as "solved".
