### ISSUE TITLE
It would be nice to be able to pass already instantiated Algod client and Indexer object references to initHumbleSDK()

### ISSUE THREAD

**Issue by LogioTek** [reach-sh/humble-sdk#39]
For initHumbleSDK() SDKOpts options object I see only Algod/Indexer server addresses/tokens/ports strings are allowed. It would be nice to be able to pass already instantiated Algod client and Indexer object references to initHumbleSDK() to avoid spooling up redundant copies internally and wasting resources and impacting performance.

**Comment by MrJackdaw** [comment]
Can you help me understand your use-case here? HumbleSDK doesn't actually use either object directly: it relies on `@reach-sh/stdlib` under the hood, which manages its own indexer and algod instances.

**Comment by jeapostrophe** [comment]
FWIW, @MrJackdaw , it is plausible that we can make this work, because Reach allows a user to set those two things --- https://docs.reach.sh/frontend/#js_setProvider

**Comment by LogioTek** [comment]
> FWIW, @MrJackdaw , it is plausible that we can make this work, because Reach allows a user to set those two things --- https://docs.reach.sh/frontend/#js_setProvider

It would be nice if the next SDK release allowed you to do the following without erroring out:

// configure Humble stdlib
const stdlib = mHumbleSDK_AMM.createReachAPI();
var stdlibProvider = stdlib.getProvider(); // get Reach stdlib provider information
stdlibProvider.algodClient = algoSDKext.GetConfigRef().algodClient; // override Algorand algod client instance
stdlibProvider.indexer = algoSDKext.GetConfigRef().indexerClient; // override Algorand indexer instance
stdlib.setProvider(stdlibProvider); // update Reach stdlib provider information, unhandledRejection: Error: Cannot re-set value once already set

**Comment by jeapostrophe** [comment]
I've finally implemented this. You may enjoy checking out this example program: https://github.com/reach-sh/reach-lang/tree/master/examples/algo-wallet-demo
