### ISSUE TITLE
Getting a strange slippage-related error when swapping, it would get stuck in loops trying and failing to execute the same transaction.

### ISSUE THREAD

**Issue by LogioTek** [reach-sh/humble-sdk#49]
```
Token Swap failed. {
  e: Error: Trader.swapBForA errored with Error: Assertion failed: Trader_swapBForA: slippage
    at ./index.rsh:495:14:application
    at ./index.rsh:519:23:application call to "doSwap" (defined at: ./index.rsh:473:57:function exp)
    at ./index.rsh:518:37:application call to [unknown function] (defined at: ./index.rsh:518:37:function exp)
    at ./index.rsh:378:19:application call to "runTrader_swapBForA0_720" (defined at: ./index.rsh:518:10:function exp)
    at ./index.rsh:378:19:application call to [unknown function] (defined at: ./index.rsh:378:19:function exp)
      at \node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\shared_impl.js:316:34
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

**Comment by LogioTek** [comment]
Example:

2022/07/12 10:36:46.583> AlgoArb: Initiating rebalancing...

2022/07/12 10:36:46.584> Humble: Selected pool Algo (0) - USDC (31566704).
2022/07/12 10:36:46.585> Humble: poolFee = 0.30%
2022/07/12 10:36:46.585> Humble: poolPrice = 0.298631 USDC (31566704) / Algo (0)
2022/07/12 10:36:46.585> Humble: priceImpact = 0.00%
2022/07/12 10:36:46.585> Humble: maxSlippage = 0.70%
2022/07/12 10:36:46.594> Humble: maxLiquidityIn = 921207.511355 USDC (31566704)
2022/07/12 10:36:46.595> Humble: maxLiquidityOut = 3084769.656328 Algo (0)
2022/07/12 10:36:46.595> Humble: nomAmountExpected = 20.226115 Algo (0)
2022/07/12 10:36:46.595> Humble: minAmountExpected = 20.023853 Algo (0)
2022/07/12 10:36:46.595> Humble: maxTradeImpact = 1.00%
2022/07/12 10:36:46.595> Humble: Swapping 6.040145 USDC (31566704) for Algo (0) with maximum slippage of 0.70%...
```
Token Swap failed. {
  e: Error: Trader.swapBForA errored with Error: Assertion failed: Trader_swapBForA: slippage
    at ./index.rsh:495:14:application
    at ./index.rsh:519:23:application call to "doSwap" (defined at: ./index.rsh:473:57:function exp)
    at ./index.rsh:518:37:application call to [unknown function] (defined at: ./index.rsh:518:37:function exp)
    at ./index.rsh:378:19:application call to "runTrader_swapBForA0_720" (defined at: ./index.rsh:518:10:function exp)
    at ./index.rsh:378:19:application call to [unknown function] (defined at: ./index.rsh:378:19:function exp)
      at \node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\shared_impl.js:316:34
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

**Comment by LogioTek** [comment]
It recalculates new slippage to use every pass through a loop so here is for example a different slippage amount it tries to use:

2022/07/12 10:39:52.913> AlgoFi: Selected pool Algo (0) - USDC (31566704).
2022/07/12 10:39:52.913> AlgoFi: poolFee = 0.25%
2022/07/12 10:39:52.914> AlgoFi: poolPrice = 0.302290 USDC (31566704) / Algo (0)
2022/07/12 10:39:52.914> AlgoFi: priceImpact = 0.00%
2022/07/12 10:39:52.914> AlgoFi: maxSlippage = 0.75%
2022/07/12 10:39:52.923> AlgoFi: nomAmountExpected = 19.965106 Algo (0)
2022/07/12 10:39:52.923> AlgoFi: minAmountExpected = 19.764454 Algo (0)
2022/07/12 10:39:52.923> AlgoFi: maxTradeImpact = 1.01%
2022/07/12 10:39:52.924> AlgoFi: Swapping 6.035252 USDC (31566704) for Algo (0) with maximum slippage of 0.75%...

**Comment by LogioTek** [comment]
I set new slippage every time before getting a swap quote:

```
try {

    mHumbleSDK_AMM.setSlippage(maxSlippage * 100); // set maximum allowed slippage in percent
}
catch (error) {

    LogError(GetAPIname() + ": " + error);
    LogError("");

    return null;
}

var swapQuote = null;

// get a pool quote
try {

    var pool_ = pool.data.pool;
    swapQuote = mHumbleSDK_AMM.calculateTokenSwap({
        pool: pool_,
        swap: { tokenAId: DeNormalizeAPIalgoAssetID(assetIdIn), amountA: amountIn, tokenBId: DeNormalizeAPIalgoAssetID(assetIdOut) }
    });

} catch (error) {

    LogError(GetAPIname() + ": " + error);
    LogError("");

    return null;
}

```
When I printout slippage I do this:

```
var actualMaxSlippage = 0;

try {

    actualMaxSlippage = mHumbleSDK_AMM.getSlippage() / 100; // set maximum allowed slippage in percent
}
catch (error) {

    LogError(GetAPIname() + ": " + error);
    LogError("");

    return null;
}

// state intention
if (!silent)
    Log(GetAPIname() + ": Swapping " + amountIn.toFixed(assetInDecimals) + " " + assetInLabel + " for " + assetOutLabel + " with maximum slippage of " + (actualMaxSlippage * 100).toFixed(2) + "%...");
```

**Comment by MrJackdaw** [comment]
Hello @LogioTek!

The error printout comes from "below" the SDK, which means the transaction was legitimately failing on the blockchain due to slippage. Here's what I think may be going on:

- `calculateTokenSwap` is a mathematical function. It relies on the pool balances you supply in the `pool` object to give you a result. _However_, 
- The `pool` object you supply to `calculateTokenSwap` is a snapshot of the pool _at the time you received_ [the object]. 

There may be a discrepancy if too much time passes between when you receive it, and when you attempt to use it in some way. And, when you _do_ use it in some way that changes the pool balance (e.g. swap, add/withdraw liquidity), you will need to re-fetch it and update your balances. 

Can you try this and let me know if it makes a difference?

**Comment by LogioTek** [comment]
That makes a lot of sense. Thanks for the tip. I coded the abstraction layer to obtain available the pools a while ago and didn't add the maintainer task to make sure pool data are up to date. I'm working with 5 different DEX SDKs at the same time on and off so things get murky which works which way haha oops.

**Comment by LogioTek** [comment]
@MrJackdaw

Hmm I went to try and add fetchLiquidityPool() to update the pool, now I'm getting a weird loader error that I never seen before and it has nothing to do with fetching LPs but with algosdk 1.18.1 update:

node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'url-parse'
Require stack:
- \src\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO_UTBC.js
- \src\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO.js
- \src\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\loader.js
- \src\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\index.js
- \src\node_modules\@reach-sh\humble-sdk\lib\index.js
- \src\targets\Humble\amm.js
- \src\core\core.js
- \src\core\AlgoArb.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (\src\node_modules\@reach-sh\humble-sdk\node_modules\@reach-sh\stdlib\dist\cjs\ALGO_UTBC.js:70:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '\\src\\node_modules\\@reach-sh\\humble-sdk\\node_modules\\@reach-sh\\stdlib\\dist\\cjs\\ALGO_UTBC.js',
    '\\src\\node_modules\\@reach-sh\\humble-sdk\\node_modules\\@reach-sh\\stdlib\\dist\\cjs\\ALGO.js',
    '\\src\\node_modules\\@reach-sh\\humble-sdk\\node_modules\\@reach-sh\\stdlib\\dist\\cjs\\loader.js',
    '\\src\\node_modules\\@reach-sh\\humble-sdk\\node_modules\\@reach-sh\\stdlib\\dist\\cjs\\index.js',
    '\\src\\node_modules\\@reach-sh\\humble-sdk\\lib\\index.js',
    '\\src\\targets\\Humble\\amm.js',
    '\\src\\core\\core.js',
    '\\src\\core\\AlgoArb.js'
  ]
}

```
{
...
  "dependencies": {
    "@algodex/algodex-sdk": "^2.0.1",
    "@algofi/amm-v0": "^1.4.2",
    "@pactfi/pactsdk": "^0.3.0",
    "@reach-sh/humble-sdk": "^2.0.0",
    "@reach-sh/stdlib": "^0.1.11-rc.0",
    "@types/node": "^17.0.45",
    "algosdk": "^1.18.1", // reverted all code changes and let dependencies update, going from 1.18.0 to 1.18.1 causes the problem above
    "tinyman-ts-sdk": "^1.0.1",
    "tslib": "^2.4.0",
    "typescript": "^4.7.4"
  }
}
```

**Comment by LogioTek** [comment]
To fix the above loader error I had to add dependency "url-parse": "^1.5.10" to my project's top level package.json but I think humble-sdk should be updated to add that dependency to its own package.json.

Now another problem is when I try to call fetchLiquidityPool() with **await** as instructed at [https://reach-sh.github.io/humble-sdk/LIQUIDITY-POOLS.html#fetchliquiditypool](https://reach-sh.github.io/humble-sdk/LIQUIDITY-POOLS.html#fetchliquiditypool):

```
var updatedPool = null;

try {

    updatedPool = await mHumbleSDK_AMM.fetchLiquidityPool(reachAccount, {
        poolAddress: pool.data.poolAddress,
        n2nn: true
    });

} catch (error) {

    LogError(GetAPIname() + ": " + error);
    LogError("");

    return null;
}
```

I get the following error:

```
\src\targets\Humble\amm.js:278
            updatedPool = await mHumbleSDK_AMM.fetchLiquidityPool(reachAccount, {
                          ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (\src\core\core.js:18:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Node.js v18.1.0
Press any key to continue...
```

And when I call fetchLiquidityPool() without **await**, I get an empty <Promise> response. What gives?

**Comment by MrJackdaw** [comment]
Hmm .. it sounds like something turned funky with your dev environment, because `url-parse` is not a required dependency (it is commonly found deep in the dependency tree). 

It is however correct that you can't call `await` in the top-level of a JS file. (Unsure what magic caused it to work before). But you can wrap your script in an `async` function, and call it at the bottom of the file:

```typescript
const updatePool = () => {
  var updatedPool = null;
  
  try {
  
      updatedPool = await mHumbleSDK_AMM.fetchLiquidityPool(reachAccount, {
          poolAddress: pool.data.poolAddress,
          n2nn: true
      });
  
  } catch (error) {
  
      LogError(GetAPIname() + ": " + error);
      LogError("");
  
      return null;
  }
}

updatedPool()
```

**Comment by LogioTek** [comment]
I think I have it sorted out now with keeping pool data up to date, it's been working without issues. Still getting error without manually adding "url-parse": "^1.5.10" dependency to my project and this started since "algosdk": "^1.18.1". This happens on 2 development environments. If I go "algosdk": "1.18.0" then there is no issue.

**Comment by MrJackdaw** [comment]
Closing as resolved; thanks for the report, and please create a new issue if one arises!
